name: Fixed Broadband Data Scraping

on:
  schedule:
    - cron: "0 8 1 * *"
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests tqdm pyspark

      - name: Run Python script
        run: python Browser_extraction.py

      - name: Commit and push changes
        run: |
          git config --local user.name "JessicaArauj"
          git config --local user.email "jessicateixeiraaraujo@gmail.com"
          git add data/*
          git diff --cached --quiet || git commit -m "Update fixed broadband data $(date '+%Y-%m-%d')"
          git push origin HEAD:main
