name: Fixed Broadband Data Scraping

on:
  schedule:
    - cron: "0 8 1 * *"  # At 08:00 UTC on the 1st day of each month
  workflow_dispatch:

jobs:
  run-python-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests tqdm pyspark

      - name: Run Python script
        run: python Browser_extraction.py

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*
          git diff --cached --quiet || git commit -m "Update fixed broadband data"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/JessicaArauj/FIEC_Test.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
